### ISSUE TITLE
Planning for more data?

### ISSUE THREAD

**Issue by romain-fontugne** [ut-dacs/Anycast-Census#1]
Hi there,
I'm just curious to know if this project is still going on and if we can expect more data in the future?

**Comment by rijswijk** [comment]
Hi Romain, I see no one has responded; yes, this is still very much going on. In fact, we are working on a more fine-grained measurement that will run more frequently, paging @raffysommy for more details.

**Comment by romain-fontugne** [comment]
Thanks Roland! Actually I did get an answer over emails :)

I'm closing this issue and looking forward for collaborations.
